# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: Rishi_PC
  demands:
   - agent.name -equals Rishi_Personal_laptop
strategy:
  matrix:
    Python37:
      python.version: '3.7.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install selenium
    pip install behave
    pip install allure-behave
  displayName: 'Install dependencies'


- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.16.1'


- task: CmdLine@2
  inputs:
    script: 'npm install -g allure-commandline'



- script: |
    behave -f allure_behave.formatter:AllureFormatter -o allure-results/ Features
  displayName: Behave

- task: CmdLine@2
  inputs:
    script: 'allure generate allure-results --clean -o allure-reports'
- task: PublishAllureReport@1
  inputs:
    reportDir: 'allure-reports'
